### ISSUE TITLE
Issue when running npcheck selecting a native-addon

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/npcheck#6]
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'node-rdkafka' of undefined`

npcheck.json:

```js
{
  "modules": [
    {
      "name": "node-rdkafka",
      "npmLink": "https://www.npmjs.com/package/node-rdkafka"
    }
  ],
  "licenses": {
    "allow": ["MIT", "Apache-2.0"]
  }
}
```

**Comment by helio-frota** [comment]
I tested with a smaller native module called deasync and got the same error:

```
Running checks on deasync

Checking if it's deprecated on NPM                                PASS 
Checking if github repository is archived                         PASS 

Checking top-level license                                        PASS 

Downloading module dependencies...
npm WARN saveError ENOENT: no such file or directory, open '/home/hf/code/foobar/npcheck-env/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/hf/code/foobar/npcheck-env/package.json'
npm WARN npcheck-env No description
npm WARN npcheck-env No repository field.
npm WARN npcheck-env No README data
npm WARN npcheck-env No license field.


> deasync@0.1.21 install /home/hf/code/foobar/npcheck-env/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting
+ deasync@0.1.21
added 4 packages from 48 contributors and audited 4 packages in 1.654s
found 0 vulnerabilities


(node:41181) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'deasync' of undefined
    at licenseTreePlugin (/home/hf/.nvm/versions/node/v14.15.4/lib/node_modules/npcheck/src/plugins/licenseTree.js:45:52)
    at async Object.run (/home/hf/.nvm/versions/node/v14.15.4/lib/node_modules/npcheck/src/cli.js:59:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:41181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alexalikiotis** [comment]
@helio-frota I think the issue here is that you're missing the `rules` field in the config which is a mandatory field even if you have no rules to specify.

```
{
  "modules": [
    {
      "name": "node-rdkafka",
      "npmLink": "https://www.npmjs.com/package/node-rdkafka"
    }
  ],
  "licenses": {
    "allow": ["MIT", "Apache-2.0"],
    "rules": {}  <-- this field is mandatory even if it's just an empty object
  }
}
```

**Comment by helio-frota** [comment]
@alexalikiotis good, thanks for the information. I added a "documentation" label to this issue to add a note about the mandatory fields :+1:
